<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ReMarkableRemember.Common\FileSystem\ReMarkableRemember.Common.FileSystem.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ReMarkableRemember.Services.DataService.Tests" />
    <InternalsVisibleTo Include="ReMarkableRemember.Tests" />
  </ItemGroup>
</Project>
