<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="ReactiveUI.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ReMarkableRemember\ReMarkableRemember.csproj" />
  </ItemGroup>

</Project>
