<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="SSH.NET" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ReMarkableRemember.Common\FileSystem\ReMarkableRemember.Common.FileSystem.csproj" />
    <ProjectReference Include="..\..\ReMarkableRemember.Common\Localization\ReMarkableRemember.Common.Localization.csproj" />
    <ProjectReference Include="..\..\ReMarkableRemember.Common\Notebook\ReMarkableRemember.Common.Notebook.csproj" />
    <ProjectReference Include="..\ConfigurationService\ReMarkableRemember.Services.ConfigurationService.csproj" />
  </ItemGroup>
</Project>
