<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>App.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Logo.ico</ApplicationIcon>
    <PackageDescription>A cross-platform management application for the reMarkable tablet</PackageDescription>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="ProDataGrid" Version="12.0.0" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="12.0.1" />
    <PackageReference Include="Svg.Controls.Avalonia" Version="12.0.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReMarkableRemember.Common\FileSystem\ReMarkableRemember.Common.FileSystem.csproj" />
    <ProjectReference Include="..\ReMarkableRemember.Common\Localization\ReMarkableRemember.Common.Localization.csproj" />
    <ProjectReference Include="..\ReMarkableRemember.Common\Notebook\ReMarkableRemember.Common.Notebook.csproj" />
    <ProjectReference Include="..\ReMarkableRemember.Services\ConfigurationService\ReMarkableRemember.Services.ConfigurationService.csproj" />
    <ProjectReference Include="..\ReMarkableRemember.Services\DataService\ReMarkableRemember.Services.DataService.csproj" />
    <ProjectReference Include="..\ReMarkableRemember.Services\HandWritingRecognitionService\ReMarkableRemember.Services.HandWritingRecognitionService.csproj" />
    <ProjectReference Include="..\ReMarkableRemember.Services\TabletService\ReMarkableRemember.Services.TabletService.csproj" />
  </ItemGroup>
</Project>
