using System;
using System.Collections.Generic;

namespace ReMarkableRemember.Services.HandWritingRecognitionService.MyScript;

internal static class MyScriptLanguages
{
    public static List<String> Supported { get; } = new List<String>()
    {
        "ar",
        "af_ZA",
        "sq_AL",
        "hy_AM",
        "az_AZ",
        "eu_ES",
        "be_BY",
        "bs_BA",
        "bg_BG",
        "ca_ES",
        "zh_CN",
        "zh_HK",
        "zh_TW",
        "hr_HR",
        "cs_CZ",
        "da_DK",
        "nl_BE",
        "nl_NL",
        "en_CA",
        "en_PH",
        "en_ZA",
        "en_GB",
        "en_US",
        "et_EE",
        "fa_IR",
        "fil_PH",
        "fi_FI",
        "fr_CA",
        "fr_FR",
        "ga_IE",
        "gl_ES",
        "ka_GE",
        "de_AT",
        "de_DE",
        "el_GR",
        "he_IL",
        "hi_IN",
        "hu_HU",
        "is_IS",
        "id_ID",
        "it_IT",
        "ja_JP",
        "kk_KZ",
        "ko_KR",
        "lv_LV",
        "lt_LT",
        "mk_MK",
        "ms_MY",
        "mn_MN",
        "pl_PL",
        "pt_BR",
        "pt_PT",
        "ro_RO",
        "ru_RU",
        "sk_SK",
        "sl_SI",
        "es_CO",
        "es_MX",
        "es_ES",
        "sv_SE",
        "tt_RU",
        "th_TH",
        "tr_TR",
        "uk_UA",
        "ur_PK",
        "vi_VN",
    };
}
