name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["linux-x64"]
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Install PupNet Deploy
      run: dotnet tool install -g KuiperZone.PupNet
    -
      name: Install PupNet Deploy dependencies
      run: sudo apt-get install -y libfuse2
    -
      name: Build AppImage
      run: pupnet -y -k appimage -r ${{ matrix.arch }}
    -
      name: Build DEB
      run: pupnet -y -k deb -r ${{ matrix.arch }}
    -
      name: Build RPM
      run: pupnet -y -k rpm -r ${{ matrix.arch }}
    -
      name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.arch }}
        path: "bin/"

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ["win-x64"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install PupNet Deploy
        run: dotnet tool install -g KuiperZone.PupNet
      -
        name: Build Setup
        run: pupnet -y -k setup -r ${{ matrix.arch }}
      -
        name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: "bin/"

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: ["osx-x64", "osx-arm64"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build
        run: dotnet publish src/ReMarkableRemember/ReMarkableRemember.csproj -c Release -r ${{ matrix.arch }} --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -o "bin/reMarkable Remember.app/Contents/MacOS"
      -
        name: Prepare Package Contents
        run: |
          mkdir "bin/reMarkable Remember.app/Contents/Resources"
          cp "assets/deployment/${{ matrix.arch }}.plist" "bin/reMarkable Remember.app/Contents/Info.plist"
          cp "assets/deployment/osx.icns" "bin/reMarkable Remember.app/Contents/Resources/icon.icns"
          rm "bin/reMarkable Remember.app/Contents/MacOS/ReMarkableRemember.xml"
      -
        name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.arch }}
            path: "bin/"
