name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["win-x86", "win-x64", "linux-x64", "osx-x64", "osx.12-arm64"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet publish ReMarkableRemember.sln -c Release -r ${{ matrix.arch }} -p:PublishReadyToRun=true --self-contained

    - name: Zip build artifacts
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ./bin/${{ matrix.arch }}.zip ./bin/Release/net7.0/${{ matrix.arch }}/publish/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish-output
        path: "./bin/*.zip"
        retention-days: 3
