name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Install PupNet Deploy
      run: dotnet tool install -g KuiperZone.PupNet
    -
      name: Install PupNet Deploy dependencies
      run: sudo apt-get install -y libfuse2
    -
      name: Build AppImage
      run: pupnet -y -k AppImage
    -
      name: Build DEB
      run: pupnet -y -k DEB
    -
      name: Build RPM
      run: pupnet -y -k RPM
    -
      name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64
        path: "bin/"

  build-windows:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install PupNet Deploy
        run: dotnet tool install -g KuiperZone.PupNet
      -
        name: Build Setup
        run: pupnet -y -k Setup
      -
        name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: "bin/"

  build-macos:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build
        run: dotnet publish src/ReMarkableRemember/ReMarkableRemember.csproj -c Release -r osx-x64 --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false
      -
        name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: osx-x64
            path: "src/ReMarkableRemember/bin/Release/net8.0/osx-x64/publish/"
