name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["linux-x64", "linux-arm64"]
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Install PupNet Deploy
      run: dotnet tool install -g KuiperZone.PupNet
    -
      name: Install PupNet Deploy dependencies
      run: sudo apt-get install -y libfuse2
    -
      name: Build AppImage
      run: pupnet -y -k appimage -r ${{ matrix.arch }}
    -
      name: Build DEB
      run: pupnet -y -k deb -r ${{ matrix.arch }}
    -
      name: Build RPM
      if: matrix.arch == 'linux-x64'
      run: pupnet -y -k rpm -r ${{ matrix.arch }}
    -
      name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.arch }}
        path: bin/

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ["win-x64", "win-arm64"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install PupNet Deploy
        run: dotnet tool install -g KuiperZone.PupNet
      -
        name: Build Setup
        run: pupnet -y -k setup -r ${{ matrix.arch }}
      -
        name: Rename Setup
        run: ren "bin/reMarkableRemember.*.exe" "reMarkableRemember-${{ matrix.arch }}.exe"
      -
        name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: bin/

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: ["osx-x64", "osx-arm64"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build Application
        run: dotnet publish src/ReMarkableRemember/ReMarkableRemember.csproj -c Release -r ${{ matrix.arch }} --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -o "bin/reMarkable Remember.app/Contents/MacOS"
      -
        name: Prepare Application Package Contents
        run: |
          mkdir "bin/reMarkable Remember.app/Contents/Resources"
          cp "assets/deployment/${{ matrix.arch }}.plist" "bin/reMarkable Remember.app/Contents/Info.plist"
          cp "assets/deployment/osx.icns" "bin/reMarkable Remember.app/Contents/Resources/icon.icns"
          rm "bin/reMarkable Remember.app/Contents/MacOS/ReMarkableRemember.xml"
      -
        name: Import Developer ID Certificate
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_P12 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_ID_CERTIFICATE_P12_PASSWORD }}
      -
        name: Store Notarization Credentials
        run: xcrun notarytool store-credentials "notarytool" --apple-id "${{ secrets.APPLE_NOTARIZE_USERNAME }}" --password "${{ secrets.APPLE_NOTARIZE_PASSWORD }}" --team-id "${{ secrets.APPLE_NOTARIZE_TEAM_ID }}"
      -
        name: Sign Application
        run: codesign --deep --force --timestamp --options=runtime --entitlements "assets/deployment/osx.entitlements" --verbose --sign "${{ secrets.APPLE_DEVELOPER_ID }}" "bin/reMarkable Remember.app"
      -
        name: Notarize Application
        run: |
          ditto -c -k --keepParent "bin/reMarkable Remember.app" "bin/reMarkable Remember.zip"
          xcrun notarytool submit "bin/reMarkable Remember.zip" --keychain-profile "notarytool" --wait
          xcrun stapler staple "bin/reMarkable Remember.app"
          rm "bin/reMarkable Remember.zip"
      -
        name: Build Disk Image
        run: |
          npm install -g appdmg
          appdmg "assets/deployment/osx.appdmg.json" "bin/reMarkable Remember.dmg"
          rm -r "bin/reMarkable Remember.app"
      -
        name: Notarize Disk Image
        run: |
          xcrun notarytool submit "bin/reMarkable Remember.dmg" --keychain-profile "notarytool" --wait
          xcrun stapler staple "bin/reMarkable Remember.dmg"
          mv "bin/reMarkable Remember.dmg" "bin/reMarkableRemember-${{ matrix.arch }}.dmg"
      -
        name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.arch }}
            path: bin/