name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install PupNet Deploy
      run: dotnet tool install -g KuiperZone.PupNet

    - name: Install PupNet Deploy dependencies
      run: sudo apt-get install -y libfuse2 dpkg rpm

    - name: Build AppImage
      run: pupnet -y -k AppImage

    - name: Build DEB
      run: pupnet -y -k DEB

    - name: Build RPM
      run: pupnet -y -k RPM

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64
        path: "deploy/Output/"

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet publish src/ReMarkableRemember.csproj -c Release -r win-x64 --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: "src/bin/Release/net8.0/win-x64/publish/"

  build-macos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x

      - name: Build
        run: dotnet publish src/ReMarkableRemember.csproj -c Release -r osx-x64 --self-contained -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: osx-x64
            path: "src/bin/Release/net8.0/osx-x64/publish/"
