name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install PupNet Deploy
      run: dotnet tool install -g KuiperZone.PupNet

    - name: Install libfuse2 for AppImage
      run: sudo apt install libfuse2

    - name: Build AppImage
      run: pupnet -y -k AppImage

    - name: Build Windows
      run: dotnet publish ReMarkableRemember.sln -c Release -r win-x64 --self-contained -p:PublishReadyToRun=true -p:DebugType=None -p:DebugSymbols=false

    - name: Build MacOS
      run: dotnet publish ReMarkableRemember.sln -c Release -r osx-x64 --self-contained -p:PublishReadyToRun=true -p:DebugType=None -p:DebugSymbols=false

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        path: "deploy/reMarkableRemember.x86_64.AppImage"

    - name: Upload Windows
      uses: actions/upload-artifact@v4
      with:
        name: reMarkableRemember.win-x64
        path: "src/bin/Release/net8.0/win-x64/publish/"

    - name: Upload MacOS
      uses: actions/upload-artifact@v4
      with:
        name: reMarkableRemember.osx-x64
        path: "src/bin/Release/net8.0/osx-x64/publish/"
