name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["win-x64", "linux-x64", "osx-x64"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet publish ReMarkableRemember.sln -c Release -r ${{ matrix.arch }} --self-contained -p:PublishReadyToRun=true -p:DebugType=None -p:DebugSymbols=false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.arch }}
        path: "./src/bin/Release/net8.0/${{ matrix.arch }}/publish/"
        retention-days: 3
